version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'daily'
    ignored_updates:
      - match:
          dependency_name: '@types/node'
          version_requirement: '>=15.x'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'all'

  - package_manager: 'javascript'
    directory: '/packages/e2e
    update_schedule: 'daily'
    ignored_updates:
      - match:
          dependency_name: '@types/node'
          version_requirement: '>=15.x'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'all'

  - package_manager: 'javascript'
    directory: '/packages/extension
    update_schedule: 'daily'
    ignored_updates:
      - match:
          dependency_name: '@types/node'
          version_requirement: '>=15.x'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'all'

  - package_manager: 'javascript'
    directory: '/packages/plugin
    update_schedule: 'daily'
    ignored_updates:
      - match:
          dependency_name: '@types/node'
          version_requirement: '>=15.x'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'all'
