name: Bump plugin version that the extension uses
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 9,18 * * *'
jobs:
  upgrade:
    name: Upgrade and commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - name: Setup Node.jobs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
      - name: Install dependencies
        run: npm run setup
      - name: Get currently installed version number
        run: echo "::set-output name=version::$(jq '.dependencies["ts-quickfixes-plugin"].version' ./packages/extension/package-lock.json -r)"
        id: current_version_check
      - name: Install latest plugin version
        run: npm i ts-quickfixes-plugin@latest
      - name: Get updated version number
        run: echo "::set-output name=version::$(jq '.dependencies["ts-quickfixes-plugin"].version' ./packages/extension/package-lock.json -r)"
        id: updated_version_check
      - name: Commit changes
        uses: EndBug/add-and-commit@v7.0.0
        with:
          add: ./packages/extension/package*.json
          branch: master
          message: 'feat(deps): update to latest plugin version ${{ steps.updated_version_check.outputs.version }}'
          pull_strategy: --rebase
          push: false
      - name: Bump extension version
        run: npx lerna exec --stream --scope ts-quickfixes-extension -- semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build extension
        run: yarn build && npx lerna run --scope ts-quickfixes-extension --stream vsce:package
      - name: Release extension
        run: npx lerna run --scope ts-quickfixes-extension --stream vsce:publish
        env:
          PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
